[package]
name = "rust-quarto"
version = "0.1.0"
authors = ["Nathaniel May <nate.may@fauna.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.6.1"