[package]
name = "testutil"
version = "0.1.0"
authors = ["Nathaniel May <nate@nathanielmay.com>"]
edition = "2018"

[dependencies.quarto]
path = "../quarto"

[dependencies]
either = "1.6.1"
quickcheck = "1"
quickcheck_macros = "1"
rand = "0.8.2"
itertools = "0.6.0"
arrayvec = "0.4.10"